const actions = {
    GET_DATA_MAN: "GET_DATA_MAN",
    GET_DATA_MAN_SUCCESS: "GET_DATA_MAN_SUCCESS",
    GET_DELTAI: "GET_DELTAI",
    GET_DELTAI_SUCCESS: "GET_DELTAI_SUCCESS",
    GET_ORDER: "GET_ORDER",
    GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS",
    ADD_CART:"ADD_CART",
    ADD_CART_SUCCESS:"ADD_CART_SUCCESS",
    DELETE_CART:"DELETE_CART",
    GET_INFO: "GET_INFO",
    GET_INFO_SUCCESS: "GET_INFO_SUCCESS",
    ADD_INFO: "ADD_INFO",
    ADD_INFO_SUCCESS: "ADD_INFO_SUCCESS",


    //login
    USER_LOGIN:'USER_LOGIN',
    USER_LOGIN_SUCCESS:'USER_LOGIN_SUCCESS',
    USER_LOGOUT:'USER_LOGOUT',
    USER_SIGNUP:'USER_SIGNUP',


    //logic database

    //BRAND
    GET_BRAND: 'GET_BRAND',
    GET_BRAND_SUCCESS: 'GET_BRAND_SUCCESS',
    EDIT_BRAND: 'EDIT_BRAND',
    DELETE_BRAND: 'DELETE_BRAND',
    ADD_BRAND: 'ADD_BRAND',
    //CART
    GET_CART: 'GET_CART',
    GET_CART_SUCCESS: 'GET_CART_SUCCESS',
    EDIT_CART: 'EDIT_CART',
    DELETE_CART: 'DELETE_CART',
    ADD_CART: 'ADD_CART',
    //ORDER
    GET_ORDER: 'GET_ORDER',
    GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS',
    EDIT_ORDER: 'EDIT_ORDER',
    DELETE_ORDER: 'DELETE_ORDER',
    ADD_ORDER: 'ADD_ORDER',
     //PRODUCT
     GET_PRODUCT: 'GET_PRODUCT',
     GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
     EDIT_PRODUCT: 'EDIT_PRODUCT',
     DELETE_PRODUCT: 'DELETE_PRODUCT',
     ADD_PRODUCT: 'ADD_PRODUCT',
      //USER
      GET_USER: 'GET_USER',
      GET_USER_SUCCESS: 'GET_USER_SUCCESS',
      EDIT_USER: 'EDIT_USER',
      DELETE_USER: 'DELETE_USER',
      ADD_USER: 'ADD_USER',
  };
  export default actions;
  